### ISSUE TITLE
IAM permissions as documented fail when building an environment for this sample.

### ISSUE THREAD

**Issue by brspurri** [awslabs/eb-docker-multiple-ports#1]
I am following the steps provided in **README** to get this sample to run.

I created (copied-and-pasted) the **IAM** json from (http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_docker_ecs.html) to create my policy and attached it to a role (which I called `aws-elasticbeanstalk-ec2-role`

However, each time I go to setup a new web-server environment in the Elastic Beanstalk console, when I select "Multi-container Docker", I see the warning: 

```
The Multi-container Docker platform requires additional EC2 Container Service permissions. The environment creation will fail if the IAM instance profile aws-elasticbeanstalk-ec2-role does not have the necessary permissions. 
```

Does anyone have any idea why the documented policy is not providing the correct permissions to run this demo app(s)?

IAM policy:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "ecs:StartTask",
        "ecs:StopTask",
        "ecs:RegisterContainerInstance",
        "ecs:DeregisterContainerInstance",
        "ecs:DiscoverPollEndpoint",
        "ecs:Submit*",
        "ecs:Poll"
       ],
      "Resource": ["*"]
    },
    {
      "Effect": "Allow",
      "Action": "s3:PutObject",
      "Resource": "arn:aws:s3:::elasticbeanstalk-*/resources/environments/logs/*"
    }
  ]
}
```

**Comment by abhiksingh** [comment]
Since, AWS IAM does not have any API's to inspect the contents of an instance profile, there is no way for Elastic Beanstalk to know if the permissions in the instance profile are correct. The warning is simply there to point out that additional permissions are required for the Multi-container Docker platform. It should not affect the functionality of your application in any way and you should be able to continue past it in the wizard.

**Comment by brspurri** [comment]
Great! Thanks for the explanation. Makes sense now.
